### ISSUE TITLE
What a coincidence! 

### ISSUE THREAD

**Issue by szepeviktor** [micropackage/dochooks#2]
I've implemented the same feature a month earlier :)

https://github.com/szepeviktor/Toolkit4WP/blob/master/src/HookAnnotation.php

**Comment by szepeviktor** [comment]
Another identical project https://github.com/dugajean/wp-hook-annotations using doctrine/annotations

**Comment by jakubmikita** [comment]
Ha! Coincidence indeed :)

I guessed there will be other projects like this, but decided to wrap it into micropackage to satisfy our own taste. We've been using dochooks for two years or so and it was a game changer.

**Comment by szepeviktor** [comment]
I was thinking about a factory that also instantiates the class.

```php
add_filter(
	$hookNameFromClassComment,
	static function () {
		$instance = new $class();
		doDocHooking();
	},
	$prio,
	0
);
```

So you don't have to unconditionally instantiate all classes.
